# hostapd.conf (AP con WPA2 + WPS PIN)
interface=wlan0
driver=nl80211
ssid=WPSnetwork
hw_mode=g
channel=6

# Seguridad WPA2-PSK
wpa=2
wpa_passphrase=passw0rd123
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# WPS
ctrl_interface=/var/run/hostapd
eap_server=1
wps_state=2
ap_setup_locked=0
device_name=MyAccessPoint
manufacturer=TestCorp
model_name=APModel
model_number=123
serial_number=12345
device_type=6-0050F204-1
uuid=12345678-9abc-def0-1234-56789abcdef0
config_methods=label display keypad push_button
# wps_cred_processing=1                             # Disable changes into this fail on run time
# wps_pin_requests=3                                # To protect against some failed tries
