interface=wlan0
ssid=WPA-EAPnetwork
channel=6
hw_mode=g
wpa=2
wpa_key_mgmt=WPA-EAP
wpa_pairwise=TKIP
rsn_pairwise=CCMP

#Radius Authentication
ieee8021x=1
eapol_version=1
eap_message="Bienvenido a la red 10.5.2.128/26"
eap_reauth_period=3600

#Radius client configuration
own_ip_addr=10.5.2.129
nas_identifier=eapwpa.in
auth_server_addr=127.0.0.1
auth_server_port=1812
auth_server_shared_secret=testing123
