ddns-update-style interim;
ignore client-updates;
authoritative;

subnet 10.5.2.192 netmask 255.255.255.192 {
    range  10.5.2.194 10.5.2.254;   				                    # Rango de IPs (10.5.2.192/26) que se repartiran entre los usuarios conectados
    option subnet-mask 255.255.255.192;    			                    # Mascara de subred que usaran los usuarios conectados
    option broadcast-address 10.5.2.255;  			                    # Dirección de broadcast usada por los usuarios coenctados
    option routers 10.5.2.193;         				                    # Gateway usado por defecto por los usuarios conectados (IP del punto de acceso)
    option domain-name-servers 10.5.2.193, 8.8.8.8, 8.8.4.4;  	        # IPs de los DNS por defecto usadas por los usuarios conectados

    default-lease-time 21600;    				                        # Tiempo en segundos hasta que expire la IP actual de cada usuario conectado
    max-lease-time 43200;
}
