network={
    ssid="WPA-EAPnetwork"
    bssid=02:00:00:00:05:00
    key_mgmt=WPA-EAP
    eap=PEAP
    identity="carlos"
    password="test"
    phase1="peaplabel=0"
    phase2="auth=MSCHAPV2"
}
