network={
    ssid="WPA-EAPnetwork"
    key_mgmt=WPA-EAP
    eap=PEAP
    identity="client1"
    password="EAPpassw0rd1"
    ca_cert="/client/ca.pem"
    phase1="peaplabel=0 tls_disable_time_checks=1"
    phase2="auth=MSCHAPV2"
}