client
dev tun
proto udp
remote 10.5.2.22 1194
resolv-retry infinite
nobind
persist-key
persist-tun
redirect-gateway def1
ca /etc/openvpn/keys/ca.crt
cert /etc/openvpn/keys/client.crt
key /etc/openvpn/keys/client.key
verb 3